version: '3.8'

services:
  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/mydatabase"
    networks:
      - app-network
    depends_on:
      - db

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - api
    command: yarn dev
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: